version: '3'
services:
  postgres:
    # Create schema:
    # docker-compose exec postgres bash -c '/docker-entrypoint-initdb.d/schema.sh'
    image: postgres:9.6
    container_name: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=inventory
    #volumes:
    # - ./data/postgres:/docker-entrypoint-initdb.d/